<div class="login">
	<form role="form" method="post" action="admin/login">
		<div class="form-group">
			<label for="exampleInputEmail1">Email address</label>
			<input type="email" class="form-control" id="exampleInputEmail1" name="email" placeholder="Enter email" required />
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Password</label>
			<input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password" required />
		</div>
		<button type="submit" class="btn btn-default">Submit</button>
	</form>
</div>