<div class="login_account">
	<h1>Iniciar Sesi&oacute;n</h1>
	<hr>
	<form id="login_form" action="#" method="post">
    	<input type="text" tabindex="1" name="user" placeholder="Usuario" class="login_text txt_usr" required />
    	<input type="password" tabindex="2" name="password" placeholder="Contraseña" class="login_text txt_pwd" required />
    	<input id="signin_button" tabindex="3" type="submit" value="Iniciar Sesión" class="login_button">
	</form>
	<div class="login_message text-danger">*Los datos son incorrectos.</div>
</div>
