<div class="row">
	<div class="img img-1"><div class="img_over over-1"></div></div>
    <div class="img img-2"><div class="img_over over-1"></div></div>
    <div class="img img-3"><div class="img_over over-1"></div></div> 	
</div>
<div class="row">
	<div class="img img-4"><div class="img_over over-1"></div></div>
    <div class="img img-5"><div class="img_over over-1"></div></div>
    <div class="img img-6"><div class="img_over over-1"></div></div> 	
</div>
<div class="row">
	<div class="img img-7"><div class="img_over over-1"></div></div>
    <div class="img img-8"><div class="img_over over-1"></div></div>
    <div class="img img-9"><div class="img_over over-1"></div></div>
</div>